### PR TITLE
Add a flame-graph charting output

### PR DESCRIPTION
**Pull request by cpennington**

### CODE REVIEW

**Comment by johnyf** [comment]
As of 47db94ed72cd398fc31bcc6dc10b4b5ad57a4464 the option `--flame` is missing from the section https://github.com/joerick/pyinstrument#i-want-to-profile-a-python-script in the README. The changes in this commit add `--flame` to that section.

**Comment by joerick** [comment]
Ooops, I didn't mean to close this, I noticed this PR was targetting `develop`, so I deleted that and it closed the PR!

**Comment by joerick** [comment]
So this kind of extension is a great fit for the architecture in 2.0, so now would be a great time to pick this PR up again. sorry that this has been neglected for so long! 😳

Any interest in picking this up again @cpennington? Otherwise I might use it for a starting point myself

**Comment by cpennington** [comment]
I've got other things on my plate at this point, but by all means take this an run with it.

**Comment by joerick** [comment]
Closing this due to inactivity - haven't gotten around to it. Flame charts can be shown using @iddan's tool https://python-flame-chart.netlify.com/ . Which reminds me, does that work with the v3.0 JSON output yet :) ?

**Comment by iddan** [comment]
Hey! Not yet but PRs are welcome. I'll try to get to it soon

**Pull request closed without merging**
