### PR TITLE
Make Profiler a context manager

### PR DESCRIPTION
**Pull request by mjpieters**
Rather than have to explicitly start and stop, use Profiler as a context manager to auto-start and stop. Test included.

### CODE REVIEW

**Comment by mjpieters** [comment]
Just found issue #15, this PR would satisfy that request.

**Comment by joerick** [comment]
Thanks for this mjpeiters! Let me have a think, I'm wondering if it would be useful to specify the output arguments in the `with` statement, so the user doesn't even need to capture the profiler object in a variable. What do you think?

**Comment by mjpieters** [comment]
You don't *have* to capture the profiler with the `as` keyword, that's optional, just like with the file objects. You can also use:

    profiler = Profiler()
    with profiler:
        # profiled code

I don't think it makes sense at all to specify the output options the `with` statement. You may want to profile separate sections, and using the profiler as a CM should just echo the way you use `.start()` and `.stop()`.

**Comment by joerick** [comment]
Fair enough. I like your second code sample the best - makes `profiler` look relevant outside the block. I think this way works best with the API as it stands :)

Thanks very much for the contribution!

**Pull request merged**
