### PR TITLE
context manager & ipython magic

### PR DESCRIPTION
**Pull request by maxim-lian**
Two features here - ipython magic, and a contextmanager. Let me know your thoughts. It probably needs some runtime checks to ensure it's being run in ipython etc

jupyter / ipython notebook usage:

``` python
import pyinstrument
%iprun long_running_calc()
```

context manager usage:

```
from pyinstrument import instrument_profile
with instrument_profile():
    long_running_calc()
```

### CODE REVIEW

**Comment by MaximilianR** [comment]
@superbobry Thanks for the comments. 

Are you involved with the project - i.e. if I make those changes will this get merged?

**Comment by superbobry** [comment]
Nope, I'm just a user. Maybe @joerick can comment?

**Comment by joerick** [comment]
Hi guys, thanks for this. I'm not a big ipython user but can see how this could be helpful, for sure. I'd like to merge this if we fix the import stuff as @superbobry mentioned, and move all the ipython code into a separate file ipython.py or similar, so it's clear that it's extending on functionality in the core of pyinstrument.

p.s. thanks for the review @superbobry!

**Comment by joerick** [comment]
Closing due to inactivity... unless you still have interest in this @maxim-lian ?

**Comment by maxim-lian** [comment]
Ah, sorry I let this drop! Particularly given it was close to the line. 

I'm not doing much profiling at the moment. That said, if there are people who would find this helpful, comment here and I'll commit to push this over the line if there's a few. 

Otherwise I may anyway when I'm profiling more

**Pull request closed without merging**
