### PR TITLE
HTML renderer: show session name in header

### PR DESCRIPTION
**Pull request by matthiasdiener**
The session name is currently only shown in the tab title, as far as I can see. The tab title is often cut off, and can't be easily copied. 

Here is how it looks like:

image

### CODE REVIEW

**Comment by joerick** [comment]
this screenshot doesn't look good, it breaks the layout.

perhaps something like this would work better?

Desktop Copy

**Comment by joerick** [comment]
font settings for this are-
image

**Comment by matthiasdiener** [comment]
> this screenshot doesn't look good, it breaks the layout.
> 
> perhaps something like this would work better?
> 
> Desktop Copy

This looks great! Do you have a patch already that shows the session like that, or would you like me to go ahead and create one?

**Comment by joerick** [comment]
i don't this was just something I mocked up in Sketch a while ago

**Comment by joerick** [comment]
so if you're interested in making a patch for this, please do!

**Comment by matthiasdiener** [comment]
Here is what I came up with:

image

**Comment by joerick** [comment]
Cheers @matthiasdiener, I just tweaked it a bit to put the code in App.svelte, I prefer to keep the 'header' component just rendering the header block.

**Comment by matthiasdiener** [comment]
Thanks @joerick ! Is there any chance for a new release? The changes in this PR and in #258 have been very useful!

**Comment by joerick** [comment]
yes, I will do soon, I have been working on 3.12 support but just merged that so I'll do a release very soon. Thanks for the ping :)

**Pull request merged**
